version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.6-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
    discovery-service:
        build: ./discovery-service
        depends_on:
            - config-service
        ports:
            - "8761:8761"
    config-service:
        build: ./config-service
        ports:
            - "8888:8888"
            - "8889:8889"
    zipkin-service:
        build: ./zipkin-service
        ports:
            - "9411:9411"
            - "9412:9412"
    auth-service:
        build: ./auth-service
        ports:
            - "9191:9191"
            - "9192:9192"
    api-gateway-service:
        build: ./api-gateway-service
        ports:
            - "80:80"
            - "81:81"
    reservation-service:
        build: ./reservation-service
        ports:
            - "8010:8010" 
            - "8011:8011" 
    user-service:
        build: ./user-service
        ports:
            - "8020:8020" 
            - "8021:8021" 
    offer-service:
        build: ./offer-service
        ports:
            - "8030:8030" 
            - "8031:8031" 